### PR TITLE
fix rebar3 path

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by jkrukoff** [comment]
Hi! Thanks for taking an interest in the library.

It looks like you are at least parially responsible for maintaining the official Erlang docker image?

I'm not sure what your goal is with the change here. For my development use, I default to a locally installed rebar3, so that I can easily pin a particular version. I've also got the `rebar3` make rule to download latest easily.

I don't really want to download a different version of rebar3 in my Dockerfile than the base, espcially one that doesn't take the same care to do so as the base image does: https://github.com/erlang/docker-erlang-otp/blob/04c7173c0762eb6432cedc65ecfd35fbb9a44341/21/Dockerfile#L54

I don't think it's unreasonable to make the Makefile default to pull rebar3 from the path, and only default to the local rebar3 if it exists. I could see that making things a bit easier for people who aren't me. I could also change my Dockerfile to use the `:21` tag instead and track latest a bit more closely.

So, here's what I could see doing in response to this PR, if I'm guessing what the intent is correctly:

1) Change the Makefile default to be from the path unless a local ./rebar3 file exists in the project directory, in which case, default to that.
2) Change the Dockerfile to pull from `:21`, in order to ensure a more up to date rebar3 (and erlang/OTP!) is used.

**Comment by jkrukoff** [comment]
I've made a set of changes to implement the above in another library with similar support files. Do you have an opinion on if this would solve what you're trying to fix here? https://github.com/jkrukoff/optic/commit/9582822bb23162cc5450a31a3cacd7fe0a999022

**Comment by getong** [comment]
As I implement this in the Feuerlabs/exometer_core#114
@tolbrino suggested that, 
```
Make it easier:
`REBAR3 ?= rebar3`
```
As using the rebar3 in the $PATH, we can just type `make` and build the code, no more need to copy rebar3 into this repo.

**Comment by jkrukoff** [comment]
I've gone ahead and merged this in, but also modified it to include the changes I've used in my other projects to default to the rebar3 in the path if there's no locally downloaded rebar3 in the repository. I think this will make things a bit more convenient, while still allowing me to easily pin rebar3 versions when needed. Please let me know if this still leaves anything unresolved for you.

**Pull request merged**
